### ISSUE TITLE
Build an 'LSOA()' object

### ISSUE THREAD

**Issue by jeremy-large** [jeremy-large/CODiT#23]
Very (suspiciously) akin to Ward() object. Probably goes in region.py.

**Comment by justin-zhida-jia** [comment]
I have added an LSOA object to lsoa_object branch.

I checked the Postal geography desriptions on ons.gov.uk/methodology/geography/ukgeographies/postalgeography
"Postcode boundaries do not align with other geographic boundaries. If a unit postcode straddles a ward (or other) boundary, you have to decide which ward to allocate the data to. "
That means there is no common unit object for both Wards and LSOAs for population allocation.
Currently number of households in multiple-households accommodation buildings are randomly allocated into apartments, terrace and residential buildings to match the number of population in each Ward.
That means if we look at the population from the LSOA view, the number of households in each LSOA might differ largely to actual number. Because we didn't consider the population distribution in LSOAs when we did the population allocation.
This might distort the number of positive cases in LSOA from actual number. 

That's why for geographic information data analysis, they usually only take one type of geographic category to best reflect their purpose rather than two types at the same time.
